"""1.6.0: add mcp

Revision ID: dc77fa5b41f6
Revises: e0e5dc8aa037
Create Date: 2025-08-06 17:01:37.276546

"""
from alembic import op
import models
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc77fa5b41f6'
down_revision = 'e0e5dc8aa037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_draft_variables',
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('app_id', models.types.StringUUID(), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('selector', sa.String(length=255), nullable=False),
    sa.Column('value_type', models.types.EnumText(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('node_execution_id', models.types.StringUUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_draft_variables_pkey')),
    sa.UniqueConstraint('app_id', 'node_id', 'name', name=op.f('workflow_draft_variables_app_id_key'))
    )
    with op.batch_alter_table('workflow_node_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('workflow_node_executions_tenant_id_idx'), ['tenant_id', 'workflow_id', 'node_id', sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('workflow_run_tenant_app_sequence_idx'))
        batch_op.drop_column('sequence_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_number', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('workflow_run_tenant_app_sequence_idx'), ['tenant_id', 'app_id', 'sequence_number'], unique=False)

    with op.batch_alter_table('workflow_node_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('workflow_node_executions_tenant_id_idx'))

    op.drop_table('workflow_draft_variables')
    # ### end Alembic commands ###
