"""empty message

Revision ID: a60b40362a5a
Revises: 669ffd70119c
Create Date: 2025-11-13 18:49:52.315757

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a60b40362a5a'
down_revision = '669ffd70119c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('quota_used',
               existing_type=mysql.BIGINT(),
               nullable=False)

    with op.batch_alter_table('trigger_oauth_system_clients', schema=None) as batch_op:
        batch_op.alter_column('plugin_id',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('trigger_oauth_system_clients', schema=None) as batch_op:
        batch_op.alter_column('plugin_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('quota_used',
               existing_type=mysql.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
